alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineImpl.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/TriggeredAlert.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/notification/NotificationFormatter.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/notification/NotificationMain.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/notification/MailNotificationServiceTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/notification/NotificationFormatterTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/notification/SlackNotificationServiceTest.scala
Get the total alert count from the query, and tweak of mail message in the notification.
=> Get the total alert count

log-example/spark-logging, log-example/spark-logging-async, log-example/spark-shell-logging, log-example/src/main/resources/log4j-async.xml
=> Add async appender example

cloudera-integration/parcel/meta/alternatives.json, collection-roller/README.md, example-configs/collection-roller/collection-roller.yml
Moved to '/etc/pulse-logging' to remove conflict with Pulse Audio config dir.
PAMS-183
=> Altered the application config dir.

README.md
Updating the README file to include the intended audience based on recommendations from #8
=> Add intended audience

alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineCliParser.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineCliParserTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala
Not setting a SMTP password in CM will cause the alert engine to skip SMTP authc.
=> Fixed the SMTP password configuration regression.

collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRoller.scala
-Included the collection name (application name) in collection roller logs.
=> Collection roller not logging collection name in 'no actions needed message

build-support/deploy.sh
=> Push correct el6 parcel in deploy

log-example/spark-shell-logging
=> Add missing backslash

log-collector/src/main/scala/io/phdata/pulse/logcollector/SolrCloudStreams.scala
The blocking solr sink should be on its own threadpool to prevent either
the stream or akka http server from blocking when the connection to solr
times out or becomes unavailable.
The new dispatcher 'solr-dispatcher' usage was validated using akka log
messages in test.
=> Put solr sink onto its own dispatcher

cloudera-integration/parcel/conf/solr-configs/pulseconfigv2/schema.xml, test-config/solr_configs/conf/schema.xml
This will allow it to show in Arcadia. Before this it would still work
as a dynamic field.
=> Add hostname to the default schema

docs/log-appender.md, docs/log-collector.md, log-collector/src/main/scala/io/phdata/pulse/logcollector/SolrCloudStreams.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/SolrCloudStreamsTest.scala
Configure the max buffer size, the size of the groups sent to Solr, and the amount of
time to wait for a group to grow before it is flushed to Solr
=> Add some configuration for the Solr stream flushing

bin/env.sh.template, log-collector/src/main/scala/io/phdata/pulse/logcollector/KerberosUtil.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollector.scala
- Scheduler to refresh the login context every 12 hours if java.security.auth.login.config is set
=> Adding class to handle kerberos ticket renewal

cloudera-integration/csd/descriptor/service.sdl, cloudera-integration/csd/scripts/control.sh
Kudu masters are used to enable metrics collection
=> Add kudu masters option

.travis.yml, build-support/deploy.sh
This is a prerequisite to pushing to Artifactory on tags
=> Build distributions in Travis build

log-collector/src/test/scala/io/phdata/pulse/logcollector/SolrCloudStreamTest.scala
- Added TestStream class in SolrCloudStreamTest.scala
- Added two test cases to verify whether flush happens after n events and n seconds
=> Add testcase for checking the stream logic in logCollector

log-appender/src/main/java/io/phdata/pulse/log/HttpManager.java
Initializing it inside the constructor leads to a null pointer exception
when other httpclients on the classpath are picked up and they try to
log with slf4j. Other http clients should not be used because they are shaded,
but something about Spark on CDH6 is causing this to happen.
=> Initialize httpclient outside of constructor

Makefile
- In jars target of makefile, added a line to copy log-example-assembly jar to the parcel
=> Add log-example appender in classpath

log-appender/src/main/scala/io/phdata/pulse/Stream.scala, log-appender/src/test/scala/io/phdata/pulse/metrics/StreamTest.scala
-In log-appender stream.scala, trait is changed into abstract class and added constructors
=> Change the trait into abstract class

docs/log-collector-kafka.md
WIP: Adding an initial draft of Log Collector Kafka documentation. Includes sample Kafka properties file and explanation of logfile->Logstash->Kafka->Solr workflow
=> Log Collector Kafka documentation

cloudera-integration/csd/descriptor/service.sdl
KAFKA_TOPIC var should be set from a csd configuration property
=> Add the property log.collector.kafka.topic
