phdata/pulse

alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRoller.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRollerCliParser.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRollerMain.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/CollectionRollerMainTest.scala
Hi Tony,
For PAMS-142, it prints as
Applications:
d2cce
89b2a
ed94a
f2558
Aliases/Collections:
Alias : 89b2a_all Collection(s) : 89b2a_1529460182
Alias : 89b2a_latest Collection(s) : 89b2a_1529460182
Alias : d2cce_all Collection(s) : d2cce_1529460182
Alias : d2cce_latest Collection(s) : d2cce_1529460182
Alias : ed94a_all Collection(s) : ed94a_1529460182
Alias : ed94a_latest Collection(s) : ed94a_1529460182
Alias : f2558_all Collection(s) : f2558_1529460182
Alias : f2558_latest Collection(s) : f2558_1529460182
when --verbose is specified. Please let me know if this is not what you had in mind. Thanks.
=> PAMS-142 and PAMS-174 changes

cloudera-integration/csd/descriptor/service.sdl, cloudera-integration/parcel/meta/alternatives.json, collection-roller/README.md, example-configs/collection-roller/collection-roller.yml
'Logger' implies a single thing, 'logging' maybe better implies the 'framework'
A little picky possibly...
=> Rename 'pulse-logger' to 'pulse-logging'

log-appender/README.md, log-appender/src/main/java/io/phdata/pulse/log/HttpAppender.java, log-appender/src/test/java/io/phdata/pulse/log/HttpAppenderTest.java
There is a JVM Shutdown hook that runs to flush any messages in the
buffer in case of application exit, but this is an extra guarantee that
error messages will be flushed in case of any application issues.
=> Always flush buffers on an ERROR message

log-appender/src/main/java/io/phdata/pulse/log/HttpAppender.java, log-appender/src/test/java/io/phdata/pulse/log/HttpAppenderTest.java, log-example/src/main/scala/io/phdata/pulse/example/SparkLog4jExample.scala
Previously adding the hostname could be done manually, but it was a
little tricky, especially for Spark applications.
If the hostname is successfully retrieved it is set in the 'properties'
of the log4j message, which is then created as a dynamic property in the
Solr index. In the future the 'hostname' should be added as a named
field to the Solr 'schema.xml'
=> Add hostname from log4j appender

cloudera-integration/parcel/conf/solr-configs/pulseconfigv2/schema.xml, test-config/solr_configs/conf/schema.xml
'text' is already the default search field (specified in solrconfig.xml).
Closes #30
=> Added copyField directives to catch-all field 'text'.

alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala
groupTriggeredAlerts case classes are built directly instead of parsing yaml file into case classes.
=> Removed yaml configuration from AlertEngineImplTest Pulse-174

collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRoller.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/CollectionRollerTest.scala
Too many collections were deleted when `deleteOldestCollection` was
being called. `appCollections.length - collectionsToKeep` was being
dropped, so if you had 8 collections and wanted to keep 7 of them, 8 - 1
= 7 of them were being dropped. This would happen every 7 days.
=> Fix too many collections deleted

log-example/src/main/scala/io/phdata/pulse/example/SparkLog4jExample.scala
Previously info and warn logs were generated by spark example and now error logging capability is also added.
=> Error logging capability added to spark logging example

collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRoller.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRollerConfigParser.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRollerMain.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/CollectionRollerTest.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/ConfigParserTest.scala
It was optional and when not set would not warn (even if there was a
misspelling). Closes #79
=> Require 'solrConfigSetDir'

cloudera-integration/csd/aux/alert-engine-default.yml, cloudera-integration/csd/aux/collection-roller-default.yml, cloudera-integration/csd/scripts/control.sh, docs/collection-roller.md
Add default configs when running the CM service for the first time.
If the user uses the safety valve or sets the path the default configs
will not be used.
Closes #78
=> Default alert and collection roller configs

cloudera-integration/parcel/conf/solr-configs/pulseconfigv2/schema.xml, test-config/solr_configs/conf/schema.xml
text_general uses solr.TextField, which doesn't support stats and is
causing errors when stats are pulled for that field. Fields aren't long
should work fine as strings.
closes #90
=> Use text_general less

build.sbt, log-appender/src/main/java/io/phdata/pulse/log/HttpAppender.java, log-example/src/main/scala/io/phdata/pulse/example/SparkLog4jExample.scala, log-example/src/main/scala/io/phdata/pulse/example/StandaloneAppExample.scala, log-example/src/test/scala/io/phdata/pams/example/SparkLog4jExampleTest.scala, log-example/src/test/scala/io/phdata/pams/example/StandaloneAppExampleTest.scala
This commit adds a JVM hook to flush the HttpAppender on shutdown. If
the appender is not flushed, messages can be left in the buffer and
lost.
Closes #94
=> Flush the appender on shutdown

collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRoller.scala, collection-roller/src/main/scala/io/phdata/pulse/collectionroller/CollectionRollerMain.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/CollectionRollerMainTest.scala, collection-roller/src/test/scala/io/phdata/pulse/collectionroller/CollectionRollerTest.scala
Using a single collection roller will:
- only upload new solr configsetdirs on application restarts
- only make a single zookeeper connection that's persisted for the
lifetime of the application
Both changes reduce the load on zookeeper and make fewer verbose logs.
=> Use a single collection roller instead of a new on on each task

log-appender/src/main/java/io/phdata/pulse/log/HttpAppender.java, log-appender/src/test/resources/log4j.properties
Log4j will allower lowercasing of the first letter so the valid params
for setting the buffer size are 'bufferSize' or 'BufferSize'. This adds
'buffersize' as a valid key.
=> Allow lower casing of buffersize paramenter

alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala, cloudera-integration/parcel/conf/solr-configs/pulseconfig-securev1/schema.xml, cloudera-integration/parcel/conf/solr-configs/pulseconfigv2/schema.xml, common/src/main/scala/io/phdata/pulse/common/DocumentConversion.scala, common/src/test/scala/io/phdata/pulse/common/SolrServiceTest.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollectorRoutes.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/PulseKafkaConsumer.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/SolrCloudStreams.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/Util.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/LogCollectorRoutesTest.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/SolrCloudStreamsTest.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/UtilTest.scala, test-config/solr_configs/conf/schema.xml
* LogCollectorRoutes
* New endpoint that parses JSON Array into Array[Map[String,String]], then sends each Map to the stream
* LogCollectorRoutesTest:
* test that takes a JSON and runs it through the new route
* Added Util Object:
* A function logEventToFlattenedMap to convert & flatten LogEvent to Map[String, String]
* Added UtilTest:
* UtilTest tests the function in Util logEventToFlattenedMap on a LogEvent
* UtilTest tests the function in Util logEventToFlattenedMap on a LogEvent with properties
* SolrCloudStreams:
* now takes Map[String,String]
* SolrCloudStreamsTest:
* test that takes Map[String,String] doc and writes to the collection, asserting that the doc count is greater than 0
* DocumentConversion:
* Added a function to convert Map[String,String] to SolrDocument
* …
=> New JSON Endpoint & refactor to use Map[String,String] instead of LogEvent

README.md
fix README typo 'build' to 'built'
=> fix README typo 'build' to 'built'

bin/env.sh.template, bin/log-collector, bin/log4j-appender-example, bin/logstash, cloudera-integration/csd/scripts/control.sh, log-collector/src/it/scala/io/phdata/pulse/logcollector/PulseKafkaConsumerTest.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollector.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollectorCliParser.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/PulseKafkaConsumer.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/LogCollectorCliParserTest.scala, log-example/src/main/resources/log4j.properties, logstash-conf/logstash-kafka.conf
WIP: Creating a new pull request since I ran into rebasing issues with old branch (feature/kafka-integration).
=> kafka-integration part 1

.travis.yml
Workaround for `WARNING: An illegal reflective access operation has
occurred`. I think what's happened is that travis has increased the
default version to JDK 9 in their scala images
=> Set explicity JDK 8

cloudera-integration/csd/descriptor/service.sdl
The heap size argument for the standard log collector was being used for
the kafka log collector
=> Fix argument for heap size

log-collector/src/main/scala/io/phdata/pulse/logcollector/KerberosUtil.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollector.scala
When using the by-name parameter the 'start' function wasn't actually
being run inside of the priveleged block, but oddly the anonymous function
works
=> Use anonymous function in Kerberos 'run' call

alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineCliParser.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineConfigParser.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineImpl.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/AlertEngineMain.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/notification/SlackNotificationService.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/trigger/AbstractAlertTrigger.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/trigger/AlertTrigger.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/trigger/SolrAlertTrigger.scala, alert-engine/src/main/scala/io/phdata/pulse/alertengine/trigger/SqlAlertTrigger.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineCliParserTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineConfigParserTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineImplTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/AlertEngineMainTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/TestObjectGenerator.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/trigger/AbstractAlertTriggerTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/trigger/SolrAlertTriggerTest.scala, alert-engine/src/test/scala/io/phdata/pulse/alertengine/trigger/SqlAlertTriggerTest.scala, build.sbt, docs/alerting-engine.md
Currently Pulse only supports a single alert engine based on Solr. Pulse needs to support configurable alert engines in general so that a JDBC alert engine can be added.
=> Add support for SQL alert triggers

log-collector/src/test/scala/io/phdata/pulse/logcollector/SolrCloudStreamTest.scala
We should remove the solr component of these streaming tests and just
test appending values to a list or something simple
@Niveditha-phData I've created a task for you to fix and re-enable these
=> Ignore some tests temporarily

bin/log4j-appender-example
Changed the sleep time from 0 to 10 ms. If we don't adjust this the log appender creates messages too fast for the log collector and solr to keep up and the log collector will die.
=> Update the log appender example to sleep for 10 ms

build.sbt, log-collector/src/main/scala/io/phdata/pulse/logcollector/JsonSupport.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/LogCollectorRoutes.scala, log-collector/src/main/scala/io/phdata/pulse/logcollector/PulseKafkaConsumer.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/LogCollectorRoutesTest.scala, log-collector/src/test/scala/io/phdata/pulse/logcollector/PulseKafkaConsumerTest.scala
Moves the json parsing out of the common package so all projects don't
need the spray json parsing. Bump akka http version.
This is an addition to the memory leak fix, in the previous fix old akka
versions were still being included on the classpath
=> Bump akka http version and simplify dependencies

log-appender/src/main/java/io/phdata/pulse/log/HttpAppender.java, log-appender/src/main/scala/io/phdata/pulse/Stream.scala, log-appender/src/test/java/io/phdata/pulse/log/HttpAppenderTest.java, log-appender/src/test/java/io/phdata/pulse/log/SLF4j.java, log-appender/src/test/scala/io/phdata/pulse/StreamTest.scala
- Initialize HttpManager in `activateOptions` so the address is not null
- Remove old HttpManager buffering code
- This removes the 'blocking' option from the configuration since
blocking in the stream is no longer possible
=> Fixes streaming buffer

log-appender/src/main/java/io/phdata/pulse/log/HttpManager.java
`DefaultConnectionKeepAliveStrategy` helps to keep the connection alive indefinitely. Successfully tested by disconnecting and reconnecting the network.
=> HttpAppender to resume after network disruption
